# Generated by Django 4.1 on 2022-09-03 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budget_core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="budgetitem",
            old_name="total",
            new_name="amount",
        ),
    ]
